# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'Stop', b' Saved as stop'), (b'InComplete', b'More information required'), (b'InExecution', b'Execution started'), (b'Error', b' Error when executed'), (b'Completed', b'Executed Successfully')], default=b'Stop', max_length=50)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('execution_start_time', models.DateTimeField(blank=True, null=True)),
                ('execution_end_time', models.DateTimeField(blank=True, null=True)),
                ('data_location', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_data_location', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=50, null=True)),
                ('columns', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='DataOperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_type', models.CharField(choices=[(b'Create', b'Create a new type'), (b'Update', b'Update a type'), (b'Filter', b'Filter a type'), (b'Delete', b'Delete a type')], max_length=50)),
                ('function_arg', models.CharField(choices=[(b'Row', b'Row of a table'), (b'Column', b'Column of a table'), (b'Table', b'Entire table'), (b'Model', b'Machine Learning Model')], max_length=50)),
                ('function_arg_id', models.CharField(blank=True, max_length=50, null=True)),
                ('function_subtype', models.CharField(choices=[(b'Add', b'Add operation'), (b'Sub', b'Sub operation'), (b'Mult', b'Mult operation'), (b'Div', b'Div operation'), (b'Normalize', b'Normalization operation'), (b'Project', b'Project certain columns'), (b'RemoveDup', b'Remove duplicates'), (b'RemoveMissing', b'Remove missing'), (b'Metadata', b'Metadata editor'), (b'Row', b'Adding a new row'), (b'Input', b'Load input data'), (b'Output', b'Dump output data'), (b'Train-Test', b'Train and test a machine learning model')], max_length=50)),
                ('function_subtype_arg', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[(b'Stop', b' Saved as stop'), (b'InComplete', b'More information required'), (b'InExecution', b'Execution started'), (b'Error', b' Error when executed'), (b'Completed', b'Executed Successfully')], default=b'Stop', max_length=50)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('execution_start_time', models.DateTimeField(blank=True, null=True)),
                ('execution_end_time', models.DateTimeField(blank=True, null=True)),
                ('component_start_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-modified_time'],
            },
        ),
        migrations.CreateModel(
            name='MLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[(b'Classifier', b'Classifier models'), (b'Clustering', b'Clustering models'), (b'Regression', b'Regression models')], max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('model_parameters', models.CharField(blank=True, max_length=50, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('max_experiments', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_data', models.CharField(max_length=100)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Experiment')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='component',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Experiment'),
        ),
        migrations.AddField(
            model_name='component',
            name='operation_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DataOperationType'),
        ),
    ]
